## Registered Users

In [15]:
import boto3
import pandas as pd
from boto3.dynamodb.conditions import Attr

# 1. Configuración de la sesión
# Si usas perfiles locales, añade profile_name='tu-perfil'
dynamodb = boto3.resource('dynamodb', region_name='us-east-1') 
table = dynamodb.Table('user_profiles')

# 2. Escaneo de la tabla
# Nota: .scan() es costoso en tablas gigantes, pero ideal para inspección rápida
response = table.scan()
items = response.get('Items', [])

# 3. Manejo de paginación (por si tienes más de 1MB de datos)
while 'LastEvaluatedKey' in response:
    response = table.scan(ExclusiveStartKey=response['LastEvaluatedKey'])
    items.extend(response.get('Items', []))

# 4. Visualización en Pandas
df = pd.DataFrame(items)

# Reordenar columnas para que el ID aparezca primero (opcional)
if not df.empty:
    cols = df.columns.tolist()
    # Cambia 'user_id' por tu Partition Key real si es distinta
    if 'user_id' in cols:
        cols.insert(0, cols.pop(cols.index('user_id')))
        df = df[cols]

print(f"Total de registros encontrados: {len(df)}")
df # Muestra las primeras 5 filas

Total de registros encontrados: 12

,user_id,city,nickname,fcm_token,urban_context,country,gender,age
0,8397dcccd645feee_1772230450825,Rosario,lucasbm,cVaZ8J4XSfG64tOgJN8zVo:APA91bHPh-5qWAYUxeaq4TT...,Suburbs,Argentina,Male,30
1,2f31ffd33f9d7ea6_1772301167972,NaN,bunny,NaN,City,Argentina,Male,<14
2,8397dcccd645feee_1772222578572,Rosario,lucasbaezm4,NaN,City,Argentina,Male,24
3,568e488267ffc3ad_1772208257363,Quilmes,Lu,NaN,Suburbs,Argentina,Female,27
4,8397dcccd645feee_1772223253226,Rosario,lucasbaez5,NaN,Suburbs,Argentina,Male,25
5,8397dcccd645feee_1772207177968,Cap Federal,lucasbaezm1,NaN,City,Argentina,Male,<14
6,8397dcccd645feee_1772236859296,Caseros,lucasbaezm7,eWGfnPX9SPqdNDRhi1-KFE:APA91bFkKyhZENoSp37QPE5...,Countryside,Argentina,Male,21
7,8397dcccd645feee_1772225125459,Rosario,Lucasbaez6,NaN,City,Argentina,Male,28
8,3b0ccc966d0a7289_1772208499305,Bernal,Mart,NaN,Suburbs,Argentina,Male,26
9,568e488267ffc3ad_1772216317571,Quilmes,Lu,NaN,Suburbs,Argentina,Female,27
10,8397dcccd645feee_1772209358752,Rosario,lucasbaezmiranda2,NaN,City,Argentina,Male,30
11,8397dcccd645feee_1772317242964,NaN,NaN,e3o_C4eJTSKE_4cqPg61oQ:APA91bF2cnQnW1Dj4Ku2Qr0...,NaN,NaN,NaN,NaN

## User Activity

In [4]:
import boto3
import pandas as pd
from boto3.dynamodb.conditions import Attr
from datetime import datetime

# 1. Configuración de la sesión
# Si usas perfiles locales, añade profile_name='tu-perfil'
dynamodb = boto3.resource('dynamodb', region_name='us-east-1') 
table = dynamodb.Table('user_activity')

# 2. Escaneo de la tabla
# Nota: .scan() es costoso en tablas gigantes, pero ideal para inspección rápida
response = table.scan()
items = response.get('Items', [])

# 3. Manejo de paginación (por si tienes más de 1MB de datos)
while 'LastEvaluatedKey' in response:
    response = table.scan(ExclusiveStartKey=response['LastEvaluatedKey'])
    items.extend(response.get('Items', []))

# 4. Visualización en Pandas
df = pd.DataFrame(items)

# Reordenar columnas para que el ID aparezca primero (opcional)
if not df.empty:
    cols = df.columns.tolist()
    # Cambia 'user_id' por tu Partition Key real si es distinta
    if 'user_id' in cols:
        cols.insert(0, cols.pop(cols.index('user_id')))
        df = df[cols]

print(f"Total de registros encontrados: {len(df)}")
df["time"] = df["timestamp"].apply(lambda x: datetime.fromtimestamp(int(x)).strftime('%d/%m/%Y %H:%M:%S')) # Muestra las primeras 5 filas
df.tail(15)

Total de registros encontrados: 78

,user_id,avg_speed_kmh,activity,latitude,longitude,timestamp,still_min,on_foot_min,on_bicycle_min,walking_min,unknown_min,in_vehicle_min,running_min,time
63,8397dcccd645feee_1772236859296,NaN,NaN,NaN,NaN,1772331960,0,0,0,0,0,0,0,28/02/2026 23:26:00
64,8397dcccd645feee_1772317242964,NaN,NaN,NaN,NaN,1772318144,0,0,0,0,0,0,0,28/02/2026 19:35:44
65,8397dcccd645feee_1772317242964,NaN,NaN,NaN,NaN,1772319045,0,0,0,0,15,0,0,28/02/2026 19:50:45
66,8397dcccd645feee_1772317242964,NaN,NaN,NaN,NaN,1772319945,0,0,0,0,15,0,0,28/02/2026 20:05:45
67,8397dcccd645feee_1772317242964,NaN,NaN,NaN,NaN,1772320845,0,0,0,0,15,0,0,28/02/2026 20:20:45
68,8397dcccd645feee_1772317242964,NaN,NaN,NaN,NaN,1772321745,0,0,0,0,15,0,0,28/02/2026 20:35:45
69,8397dcccd645feee_1772317242964,NaN,NaN,NaN,NaN,1772322878,0,0,0,0,18,0,0,28/02/2026 20:54:38
70,8397dcccd645feee_1772317242964,NaN,NaN,NaN,NaN,1772323798,0,0,0,0,15,0,0,28/02/2026 21:09:58
71,8397dcccd645feee_1772317242964,NaN,NaN,NaN,NaN,1772324992,0,0,0,0,19,0,0,28/02/2026 21:29:52
72,8397dcccd645feee_1772317242964,NaN,NaN,NaN,NaN,1772325892,0,0,0,0,15,0,0,28/02/2026 21:44:52
73,8397dcccd645feee_1772317242964,NaN,NaN,NaN,NaN,1772326799,0,0,0,0,15,0,0,28/02/2026 21:59:59
74,8397dcccd645feee_1772317242964,NaN,NaN,NaN,NaN,1772327703,0,0,0,0,15,0,0,28/02/2026 22:15:03
75,8397dcccd645feee_1772317242964,NaN,NaN,NaN,NaN,1772328603,0,0,0,0,15,0,0,28/02/2026 22:30:03
76,8397dcccd645feee_1772317242964,NaN,NaN,NaN,NaN,1772329509,0,0,0,0,15,0,0,28/02/2026 22:45:09
77,8397dcccd645feee_1772317242964,NaN,NaN,NaN,NaN,1772330423,0,0,0,0,15,0,0,28/02/2026 23:00:23

In [ ]:
import boto3
import pandas as pd
from boto3.dynamodb.conditions import Attr

# 1. Configuración de la sesión
# Si usas perfiles locales, añade profile_name='tu-perfil'
dynamodb = boto3.resource('dynamodb', region_name='us-east-1') 
table = dynamodb.Table('user_steps')

# 2. Escaneo de la tabla
# Nota: .scan() es costoso en tablas gigantes, pero ideal para inspección rápida
response = table.scan()
items = response.get('Items', [])

# 3. Manejo de paginación (por si tienes más de 1MB de datos)
while 'LastEvaluatedKey' in response:
    response = table.scan(ExclusiveStartKey=response['LastEvaluatedKey'])
    items.extend(response.get('Items', []))

# 4. Visualización en Pandas
df = pd.DataFrame(items)

# Reordenar columnas para que el ID aparezca primero (opcional)
if not df.empty:
    cols = df.columns.tolist()
    # Cambia 'user_id' por tu Partition Key real si es distinta
    if 'user_id' in cols:
        cols.insert(0, cols.pop(cols.index('user_id')))
        df = df[cols]

print(f"Total de registros encontrados: {len(df)}")
df["time"] = df["timestamp"].apply(lambda x: datetime.fromtimestamp(int(x)).strftime('%d/%m/%Y %H:%M:%S')) # Muestra las primeras 5 filas
df.sort_values(by="timestamp", ascending=False, inplace=True)
df.to_excel("data_user_steps.xlsx", index=False)

Total de registros encontrados: 2332

,user_id,steps,timestamp,latitude,longitude,time
1539,8397dcccd645feee_1772332603557,29386,1772334009,NaN,NaN,01/03/2026 00:00:09
1538,8397dcccd645feee_1772332603557,29386,1772333992,NaN,NaN,28/02/2026 23:59:52
1537,8397dcccd645feee_1772332603557,29386,1772333770,NaN,NaN,28/02/2026 23:56:10
1536,8397dcccd645feee_1772332603557,29386,1772333247,-34.6543647,-58.5326029,28/02/2026 23:47:27
1535,8397dcccd645feee_1772332603557,29386,1772332656,NaN,NaN,28/02/2026 23:37:36
1534,8397dcccd645feee_1772332603557,29386,1772332636,NaN,NaN,28/02/2026 23:37:16
2280,8397dcccd645feee_1772332441660,29386,1772332500,NaN,NaN,28/02/2026 23:35:00
2279,8397dcccd645feee_1772332441660,29386,1772332490,NaN,NaN,28/02/2026 23:34:50
2278,8397dcccd645feee_1772332441660,29386,1772332481,NaN,NaN,28/02/2026 23:34:41
1533,8397dcccd645feee_1772236859296,67619,1772331969,NaN,NaN,28/02/2026 23:26:09